dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install github.com/onsi/ginkgo/ginkgo  # installs the ginkgo CLI
  - go install github.com/onsi/gomega/...     # fetches the matcher library

script:
  - golangci-lint run --config=.golangci-lint.yaml # run a bunch of code checkers/linters in parallel
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress
  - GOOS=linux go build # target the container environment

  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=smartatransit/scrapedumper
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "staging" ; fi`
  - docker build . -t $REPO:${TRAVIS_COMMIT::8}
  - docker tag $REPO:${TRAVIS_COMMIT::8} $REPO:$TAG
  - docker tag $REPO:${TRAVIS_COMMIT::8} $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO:$TAG

after_success:
  - touch coverage.txt; find . -name "*.coverprofile" | xargs -l cat >> coverage.txt
  - curl -s https://codecov.io/bash | bash -
